name: Playwright Tests
trigger:
  - main
  - master
matrix:
  linux:
    imageName: "ubuntu-latest"
  mac:
    imageName: "macOS-latest"
  windows:
    imageName: "windows-latest"

jobs:
  - job: test
    timeoutInMinutes: 60
    strategy:
    pool:
      vmImage: $(imageName)
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "16.x"
        displayName: "Install Node.js"
      - script: |
          npm ci
        displayName: "Install dependencies"
      - script: |
          npx playwright install --with-deps
        displayName: "Install Playwright Browsers"
      - script: |
          npx playwright test
        displayName: "Run Playwright tests"
      # - task: PublishHtmlReport@1
      #   displayName: Publish Html Report
      #   inputs:
      #     tabName: Playwright Report
      #     reportDir: playwright-report/windows/index.html
      - task: PublishTestResults@2
        displayName: "Publish test results"
        inputs:
          searchFolder: "test-results"
          testResultsFormat: "JUnit"
          testResultsFiles: "e2e-junit-results.xml"
          mergeTestResults: true
          failTaskOnFailedTests: true
          testRunTitle: "My End-To-End Tests"
        condition: succeededOrFailed()
