name: Playwright Tests
trigger:
  - main
  - master
jobs:
  - job: test
    timeoutInMinutes: 60
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "16.x"
        displayName: "Install Node.js"
      - script: |
          npm ci
        displayName: "Install dependencies"
      - script: |
          npx playwright install --with-deps
        displayName: "Install Playwright Browsers"
      - script: |
          npx playwright test
        displayName: "Run Playwright tests"
      - task: PublishHtmlReport@1
        displayName: Publish Html Report
        inputs:
          tabName: Playwright Report
          reportDir: playwright-report/windows/index.html
        