trigger:
  branches:
    include:
      - main
      - master

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: "16.x"
  displayName: 'Use Node.js 16.x'

- script: |
    npm ci
  displayName: 'Install dependencies'

- script: |
    npx playwright install --with-deps
  displayName: 'Install Playwright Browsers'

- script: |
    npx playwright test --browser=all
  displayName: 'Run Playwright tests'

