trigger:
  branches:
    include:
    - main
    - master

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: 14.x
  displayName: 'Use Node.js 14.x'

- script: |
    npx playwright install 
  displayName: 'Install Playwright'

- script: |
    npx playwright test --browser=all
  displayName: 'Run Playwright tests on all browsers'