strategy:
  matrix:
    windows:
      vmImage: windows-latest
    ubuntu:
      vmImage: ubuntu-latest
    macos:
      vmImage: macos-latest

jobs:
- job: Job_1
  displayName: 'Run Test'
  pool:
    vmImage: ${{ matrix.vmImage }}
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: NodeTool@0
    displayName: Node Installation
    inputs:
      versionSpec: 16.x
  - task: CmdLine@2
    displayName: Install PlayWright
    inputs:
      script: npm i && npx playwright install
      workingDirectory: $(BuildParameters.workingDirectory)
  - task: Npm@1
    displayName: Execute Test
    inputs:
      command: custom
      workingDir: $(BuildParameters.workingDir)
      verbose: false
      customCommand: run windowtest
  - task: PublishHtmlReport@1
    displayName: Publish Html Report
    inputs:
      tabName: Playwright Report
      reportDir: playwright-report/${{ matrix.vmImage }}/index.html
