import { test, expect } from '@playwright/test';
test('test', async ({ page }) => {
  await page.goto('https://parabank.parasoft.com/parabank/index.htm');
  await page.getByRole('link', { name: 'Register' }).click();
  await page.locator('input[name="customer\\.firstName"]').click();
  await page.locator('input[name="customer\\.firstName"]').fill('teemo');
  await page.locator('input[name="customer\\.firstName"]').press('Tab');
  await page.locator('input[name="customer\\.lastName"]').click();
  await page.locator('input[name="customer\\.lastName"]').fill('motee');
  await page.locator('input[name="customer\\.address\\.street"]').click();
  await page.locator('input[name="customer\\.address\\.street"]').fill('teeCountry');
  await page.locator('input[name="customer\\.address\\.city"]').click();
  await page.locator('input[name="customer\\.address\\.city"]').fill('teeC');
  await page.locator('input[name="customer\\.address\\.state"]').click();
  await page.locator('input[name="customer\\.address\\.state"]').fill('Teeee');
  await page.locator('input[name="customer\\.address\\.zipCode"]').click();
  await page.locator('input[name="customer\\.address\\.zipCode"]').fill('123121');
  await page.locator('input[name="customer\\.phoneNumber"]').click();
  await page.locator('input[name="customer\\.phoneNumber"]').fill('828192932');
  await page.locator('input[name="customer\\.ssn"]').click();
  await page.locator('input[name="customer\\.ssn"]').fill('2131223');
  await page.locator('input[name="customer\\.username"]').click();
  await page.locator('input[name="customer\\.username"]').fill('playwrightTest');
  await page.locator('input[name="customer\\.password"]').click();
  await page.locator('input[name="customer\\.password"]').fill('pt123');
  await page.locator('input[name="repeatedPassword"]').click();
  await page.locator('input[name="repeatedPassword"]').fill('pt123');
  await page.getByRole('button', { name: 'Register' }).click();
  await expect(page).toHaveURL('https://parabank.parasoft.com/parabank/register.htm');
  await page.getByRole('link', { name: 'Log Out' }).click();
  await expect(page).toHaveURL('https://parabank.parasoft.com/parabank/index.htm?ConnType=JDBC');
});